name: Node.js Package

on:
  push:
    branchs: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://npm.pkg.github.com"

      - name: Build Project
        run: |
          npm install
          npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
